baseURL = "https://haproxy-ingress.github.io"
title = "HAProxy Ingress"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Needed to display the home page properly
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = ""

# Language configuration

[languages]
[languages.en]
title = "HAProxy Ingress"
description = "Ingress controller implementation for HAProxy load balancer"
languageName = "English"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/jcmoraisjr/haproxy-ingress"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/jcmoraisjr/haproxy-ingress"

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "docs"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = ""

[params]
copyright = "The HAProxy Ingress Controller Authors"
privacy_policy = ""

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "v0.14"

[[params.versions]]
version = "Latest"
url = "https://haproxy-ingress.github.io/docs"

[[params.versions]]
version = "v0.14"
url = "https://haproxy-ingress.github.io/v0.14/docs"

[[params.versions]]
version = "v0.13"
url = "https://haproxy-ingress.github.io/v0.13/docs"

[[params.versions]]
version = "v0.12"
url = "https://haproxy-ingress.github.io/v0.12/docs"

[[params.versions]]
version = "v0.10"
url = "https://haproxy-ingress.github.io/v0.10/docs"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/jcmoraisjr/haproxy-ingress/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/jcmoraisjr/haproxy-ingress/issues/new">tell us how we can improve</a>.'

[params.links]

# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
name = "Slack"
url = "https://kubernetes.slack.com/channels/haproxy-ingress"
icon = "fab fa-slack"
desc = "We're in the #haproxy-ingress channel on Kubernetes Slack. Invites at https://slack.k8s.io if not subscribed."

[[params.links.user]]
name = "Users mailing list"
url = "https://groups.google.com/forum/#!forum/haproxy-ingress"
icon = "fa fa-envelope"
desc = "Announcements and discussion on a mailing list"

[[params.links.user]]
name = "Stack Overflow"
url = "https://stackoverflow.com/questions/tagged/haproxy-ingress"
icon = "fab fa-stack-overflow"
desc = "Practical questions and curated answers"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/jcmoraisjr/haproxy-ingress"
icon = "fab fa-github"
desc = "Development takes place here!"
